%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\yxiao.GACL\OneDrive - University of Arkansas\03_Strath_Inv_publication\Mission_profile\Altitude_speed_time.xlsx
%    Worksheet: EXY7199
%
% Auto-generated by MATLAB on 25-Mar-2026 09:32:54

clear all
clc

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = "EZY7200";
opts.DataRange = "A2:H281";

% Specify column names and types
opts.VariableNames = ["Time", "Latitude", "longtitude", "Direction", "Var5", "Speed_km_h_", "Altitude_m_", "Var8"];
opts.VariableTypes = ["string", "double", "double", "categorical", "double", "double", "double", "categorical"];

% Specify variable properties
opts = setvaropts(opts, "Time", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Time", "Direction", "Var8"], "EmptyFieldRule", "auto");

% Import the data
Altitude_speed_time = readtable("Altitude_speed_time.xlsx", opts, "UseExcel", false);


% Clear temporary variables
clear opts

Time_HH_MM_SS = erase(Altitude_speed_time.Time,'星期一 ');
Time_SS = datevec(Time_HH_MM_SS,'HH:MM:SS');
Time = Time_SS(:,4) * 3600 + Time_SS(:,5) * 60 + Time_SS(:,6) ...
    - (Time_SS(1,4) * 3600 + Time_SS(1,5) * 60 + Time_SS(1,6));

Directionstring = string(Altitude_speed_time.Direction);
Direction_str = regexp(Directionstring,'\d+','match');
Direction_num = zeros(size(Time,1),1);
for i = 1:1:size(Time,1)
    Direction_num(i,1) = str2double(Direction_str{i});
end

% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 13);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:M15";

% Specify column names and types
opts.VariableNames = ["Altitude_m", "Speed1", "Speed2", "Speed3", "Speed4", "Speed5", "Speed6_knot", "Angle1", "Angle2", "Angle3", "Angle4", "Angle5", "Angle6_degree"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
Wind_speed = readtable("WInd_speed.xlsx", opts, "UseExcel", false);


% Clear temporary variables
clear opts

% %%
% font_size = 14;
% font_name = 'Times New Roman';
% 
% figure
% yyaxis left
% p = plot(Time,Altitude_speed_time.Altitude_m_ / max(Altitude_speed_time.Altitude_m_));
% p(1).LineWidth = 1;
% xlabel('Flight time [s]','FontName',font_name,'FontSize',font_size)
% ylabel({'Altitude [p.u.]'},'FontName',font_name,'FontSize',font_size)
% % xlim([-5e-6,5e-6])
% % xticks(0:1000:8000);
% % xticklabels({'','','','','','','','',''});
% set(get(gca,'ylabel'),'rotation',90,'VerticalAlignment','middle','HorizontalAlignment','right')
% ylim([-0.1,1.1])
% grid on
% grid minor
% 
% yyaxis right
% p = plot(Time,Altitude_speed_time.Speed_km_h_ / max(Altitude_speed_time.Speed_km_h_));
% p(1).LineWidth = 1;
% % % xlabel('Time [\mus]','FontName',font_name,'FontSize',font_size)
% ylabel({'Speed [p.u.]'},'FontName',font_name,'FontSize',font_size)
% % xlim([-5e-6,5e-6])
% % xticks(-5e-6:1e-6:5e-6);
% % xticklabels({'-5','-4','-3','-2','-1','0','1','2','3','4','5'});
% set(get(gca,'ylabel'),'rotation',270,'VerticalAlignment','middle','HorizontalAlignment','left')
% ylim([-0.1,1.1])
% grid on
% grid minor

%% Power estimation
% Flight data from FlightAware
% EZY7200 23-Mar-2026, EDI - BCN
% Departure time 16:18:45
% Arrival time 18:32:42
% Aircraft Airbus A319
% Equations based on E. M. Greitzer, Z. S. Spakovszky, and I. A. Waitz, 
% Thermodynamics and Propulsion. [Online]. Cambridge, MA, USA: Dept. Aeronaut. Astronaut., MIT. 
% Available: https://web.mit.edu/16.unified/www/FALL/thermodynamics/notes/notes.html [Accessed: Mar. 25, 2026].


% Constant parameters
T_MSL = 288.15; % Average ambient temperature at mean sea level, K
Pres_MSL = 101324;  % Average ambient pressure at mean sea level, Pa
Rd = 287.05;    % specific gas constant for dry air, J/(kg*K)
S_aircraft = 122.4; % Wing reference area of A319, m2
W_aircraft = 75.5e3;    % Maximum takeoff weight of A319, kg
e_Oswald = 0.8;
CD0_aircraft = 0.02;    % Zero-lift drag coefficient of A319
Wingspan_aircraft = 35.8;   % Wingspan of A319, m
AR_aircraft = Wingspan_aircraft ^ 2 / S_aircraft;   % Aspect ratio of A319
Velo_air_ground = 45 * 1000 / 3600;    % mean air speed at sea level, m/s
Flight_distance = 0;    % Total flight distance, m
for j = 1:1:size(Time,1)-1
    Flight_distance = Flight_distance + Altitude_speed_time.Speed_km_h_(j) ...
        * 1000 / 3600 * (Time(j + 1) - Time(j)); 
end

P_array = zeros(size(Time,1),1);
Distance_flew = 0;

for k = 1:1:size(Time,1)
    
    Alt = Altitude_speed_time.Altitude_m_(k);   % Altitude of aircraft, m
    Velo = Altitude_speed_time.Speed_km_h_(k) * 1000 / 3600;  % Ground speed of aircraft, m/s

    if k > 1
        Distance_flew = Distance_flew + Velo * (Time(k) - Time(k - 1)); % Total distance flew, m
    end

    if (Distance_flew <= Flight_distance / 3)
        areaIndex = 3;
    elseif (Distance_flew > Flight_distance / 3) && (Distance_flew <= Flight_distance * 2 / 3)
        areaIndex = 2;
    else
        areaIndex = 1;
    end

    [~,sortIndices] = sort(abs(Wind_speed.Altitude_m - Alt));
    % Extract first and second closest values
    UpperIndice = max(sortIndices(1),sortIndices(2));
    LowerIndice = min(sortIndices(1),sortIndices(2));

    Velo_air_UpperAve = (Distance_flew - (3 - areaIndex) * Flight_distance / 3) ...
        / (Flight_distance / 3) * Wind_speed.(append('Speed',num2str(areaIndex)))(UpperIndice) + ...
        ((4 - areaIndex) * Flight_distance / 3 - Distance_flew) ...
        / (Flight_distance / 3) * Wind_speed.(append('Speed',num2str(areaIndex + 1)))(UpperIndice);
    Velo_air_LowerAve = (Distance_flew - (3 - areaIndex) * Flight_distance / 3) ...
        / (Flight_distance / 3) * Wind_speed.(append('Speed',num2str(areaIndex)))(LowerIndice) + ...
        ((4 - areaIndex) * Flight_distance / 3 - Distance_flew) ...
        / (Flight_distance / 3) * Wind_speed.(append('Speed',num2str(areaIndex + 1)))(LowerIndice);
    Angle_air_UpperAve = (Distance_flew - (3 - areaIndex) * Flight_distance / 3) ...
        / (Flight_distance / 3) * Wind_speed.(append('Angle',num2str(areaIndex)))(UpperIndice) + ...
        ((4 - areaIndex) * Flight_distance / 3 - Distance_flew) ...
        / (Flight_distance / 3) * Wind_speed.(append('Angle',num2str(areaIndex + 1)))(UpperIndice);
    Angle_air_LowerAve = (Distance_flew - (3 - areaIndex) * Flight_distance / 3) ...
        / (Flight_distance / 3) * Wind_speed.(append('Angle',num2str(areaIndex)))(LowerIndice) + ...
        ((4 - areaIndex) * Flight_distance / 3 - Distance_flew) ...
        / (Flight_distance / 3) * Wind_speed.(append('Angle',num2str(areaIndex + 1)))(LowerIndice);

    Alt_interval = Wind_speed.Altitude_m(UpperIndice) - Wind_speed.Altitude_m(LowerIndice);
    % Amplitude of air speed, m/s
    Velo_air = 1.852 * 1000 / 3600 * ((Alt - Wind_speed.Altitude_m(LowerIndice)) / Alt_interval * Velo_air_UpperAve ...
        + (Wind_speed.Altitude_m(UpperIndice) - Alt) / Alt_interval * Velo_air_LowerAve); 
    % Angle of air speed, degrees, relative to north
    Direction_air = ((Alt - Wind_speed.Altitude_m(LowerIndice)) / Alt_interval * Angle_air_UpperAve ...
        + (Wind_speed.Altitude_m(UpperIndice) - Alt) / Alt_interval * Angle_air_LowerAve);
    Velo_TAS = Velo - Velo_air * cos((Direction_num(k) - Direction_air) / 180 * pi);    % True airspeed of the aircaft, m/s
    
    % Ambient temperature and pressure
    Pres_amb = Pres_MSL * (1 - 0.0065 * Alt / T_MSL) ^ 5.2561;  % Ambient pressure, Pa
    T_amb = T_MSL - 6.5 * Alt / 1000 + 24 * (1 - Alt / 42361);  % Ambient temperature, K
    rho_air = Pres_amb / (Rd * T_amb);  % Density of Air, kg/m3

    D_aircraft = 1 / 2 * rho_air * Velo_TAS ^ 2 * S_aircraft * CD0_aircraft ...
        + W_aircraft ^ 2 / (1 / 2 * rho_air * Velo_TAS ^ 2 * S_aircraft) * (1 / (pi * e_Oswald * AR_aircraft)); % drag force of aircraft, N
    P_aircraft = D_aircraft * Velo_TAS; % Propulsion power of aircraft, W
    P_array(k,1) = P_aircraft;
end


% figure
% p = plot(Time,P_array / 1e6);
% p(1).LineWidth = 1;
% xlabel('Flight time [s]','FontName',font_name,'FontSize',font_size)
% ylabel({'Power [MW]'},'FontName',font_name,'FontSize',font_size)
% % xlim([-5e-6,5e-6])
% % xticks(0:1000:8000);
% % xticklabels({'','','','','','','','',''});
% set(get(gca,'ylabel'),'rotation',90,'VerticalAlignment','middle','HorizontalAlignment','right')
% %ylim([-0.1,1.1])
% grid on
% grid minor

%%
% Time_mission = Time;    % Time in s.
% Power_mission = P_array / (1e6);    % Power in MW
% Altitude_mission = Altitude_speed_time.Altitude_m_ / 1000; % Altitude in km
% Speed_mission = Altitude_speed_time.Speed_km_h_;    % Speed in km/h
% save('Power_time.mat','Time_mission','Power_mission','Speed_mission','Altitude_mission');

%%
font_size = 14;
font_name = 'Times New Roman';

% figure
% yyaxis left
% p = plot(Time,P_array / (1e6));
% p(1).LineWidth = 1;
% xlabel('Flight time [s]','FontName',font_name,'FontSize',font_size)
% ylabel({'Power [MW]'},'FontName',font_name,'FontSize',font_size)
% % xlim([-5e-6,5e-6])
% % xticks(0:1000:8000);
% % xticklabels({'','','','','','','','',''});
% set(get(gca,'ylabel'),'rotation',90,'VerticalAlignment','middle','HorizontalAlignment','right')
% %ylim([-0.1,1.1])
% grid on
% grid minor
% 
% yyaxis right
% p = stackedplot(Time,[Altitude_speed_time.Speed_km_h_,Altitude_speed_time.Altitude_m_/1000]);
% p(1).LineWidth = 1;
% % % xlabel('Time [\mus]','FontName',font_name,'FontSize',font_size)
% ylabel({'Ground speed [km/h]'},'FontName',font_name,'FontSize',font_size)
% % xlim([-5e-6,5e-6])
% % xticks(-5e-6:1e-6:5e-6);
% % xticklabels({'-5','-4','-3','-2','-1','0','1','2','3','4','5'});
% set(get(gca,'ylabel'),'rotation',270,'VerticalAlignment','middle','HorizontalAlignment','left')
% %ylim([-0.1,1.1])
% grid on
% grid minor

ylabels{1}='Power [MW]';
ylabels{2}='Ground Speed [km/h]';
ylabels{3}='Altitude [km]';
[ax,hlines] = plotyyy(Time,P_array / (1e6),Time,Altitude_speed_time.Speed_km_h_,Time,Altitude_speed_time.Altitude_m_/1000,ylabels);
